baseURL = "https://natrium11321.github.io/alglib/"
title = "Algorithm Library"

# Set language
languageCode = "ja-JP"
defaultContentLanguage = "ja"
hasCJKLanguage = true

# Set theme
theme = "book"
googleAnalytics = "UA-116837367-3"
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  BookToC = false          # Hide ToC
  BookSearch = false       # Disable search function
  BookSection = "*"        # Show all menus

# Set code highlight
[markup]
  [markup.highlight]
    style = "lovelace"

# Open link in new tab
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
